# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1888, 987)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.black_bg = QtWidgets.QLabel(self.centralwidget)
        self.black_bg.setGeometry(QtCore.QRect(-250, -150, 2271, 1151))
        self.black_bg.setText("")
        self.black_bg.setPixmap(QtGui.QPixmap("G.U.I Material/B.G/Black_Template.jpg"))
        self.black_bg.setScaledContents(True)
        self.black_bg.setObjectName("black_bg")


        self.bg_2 = QtWidgets.QLabel(self.centralwidget)
        self.bg_2.setGeometry(QtCore.QRect(10, 10, 601, 421))
        self.bg_2.setStyleSheet("background-color: rgb(85, 0, 255);")
        self.bg_2.setText("")
        self.bg_2.setObjectName("bg_2")


        self.gif_1 = QtWidgets.QLabel(self.centralwidget)
        self.gif_1.setGeometry(QtCore.QRect(20, 20, 581, 401))
        self.gif_1.setText("")
        self.gif_1.setPixmap(QtGui.QPixmap("G.U.I Material/ExtraGui/Health_Template.gif"))
        self.gif_1.setScaledContents(True)
        self.gif_1.setObjectName("gif_1")


        self.gif_3 = QtWidgets.QLabel(self.centralwidget)
        self.gif_3.setGeometry(QtCore.QRect(10, 440, 621, 451))
        self.gif_3.setText("")
        self.gif_3.setPixmap(QtGui.QPixmap("G.U.I Material/ExtraGui/Jarvis_Gui (2).gif"))
        self.gif_3.setScaledContents(True)
        self.gif_3.setObjectName("gif_3")


        self.gif_2 = QtWidgets.QLabel(self.centralwidget)
        self.gif_2.setGeometry(QtCore.QRect(1500, -20, 381, 161))
        self.gif_2.setText("")
        self.gif_2.setPixmap(QtGui.QPixmap("G.U.I Material/ExtraGui/initial.gif"))
        self.gif_2.setScaledContents(True)
        self.gif_2.setObjectName("gif_2")


        self.gif_4 = QtWidgets.QLabel(self.centralwidget)
        self.gif_4.setGeometry(QtCore.QRect(1330, 550, 691, 471))
        self.gif_4.setText("")
        self.gif_4.setPixmap(QtGui.QPixmap("G.U.I Material/VoiceReg/Siri_1.gif"))
        self.gif_4.setScaledContents(False)
        self.gif_4.setObjectName("gif_4")


        self.gif_5 = QtWidgets.QLabel(self.centralwidget)
        self.gif_5.setGeometry(QtCore.QRect(520, 430, 581, 521))
        self.gif_5.setText("")
        self.gif_5.setPixmap(QtGui.QPixmap("G.U.I Material/B.G/Iron_Template_1.gif"))
        self.gif_5.setScaledContents(True)
        self.gif_5.setObjectName("gif_5")


        self.bg_3 = QtWidgets.QLabel(self.centralwidget)
        self.bg_3.setGeometry(QtCore.QRect(930, 10, 551, 201))
        self.bg_3.setText("")
        self.bg_3.setPixmap(QtGui.QPixmap("G.U.I Material/ExtraGui/B.G_Template_1.gif"))
        self.bg_3.setScaledContents(True)
        self.bg_3.setObjectName("bg_3")


        self.gif_6 = QtWidgets.QLabel(self.centralwidget)
        self.gif_6.setGeometry(QtCore.QRect(1430, 130, 531, 431))
        self.gif_6.setText("")
        self.gif_6.setPixmap(QtGui.QPixmap("G.U.I Material/ExtraGui/Earth.gif"))
        self.gif_6.setScaledContents(True)
        self.gif_6.setObjectName("gif_6")


        self.text_time = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_time.setGeometry(QtCore.QRect(620, 10, 291, 61))
        self.text_time.setStyleSheet("background-color: Transparent;\n" "")
        self.text_time.setObjectName("text_time")


        self.gif_7 = QtWidgets.QLabel(self.centralwidget)
        self.gif_7.setGeometry(QtCore.QRect(980, 380, 561, 521))
        self.gif_7.setText("")
        self.gif_7.setPixmap(QtGui.QPixmap("G.U.I Material/ExtraGui/jarvis breaking.gif"))
        self.gif_7.setScaledContents(True)
        self.gif_7.setObjectName("gif_7")


        self.text_temp = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_temp.setGeometry(QtCore.QRect(620, 150, 291, 61))
        self.text_temp.setStyleSheet("background-color: Transparent;\n"
"")
        self.text_temp.setObjectName("text_temp")


        self.text_date = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_date.setGeometry(QtCore.QRect(620, 80, 291, 61))
        self.text_date.setStyleSheet("background-color: Transparent;\n"
"")
        self.text_date.setObjectName("text_date")


        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setGeometry(QtCore.QRect(30, 910, 221, 51))
        self.start_btn.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 21pt \"MS Serif\";")
        self.start_btn.setObjectName("start_btn")


        self.bg_4 = QtWidgets.QLabel(self.centralwidget)
        self.bg_4.setGeometry(QtCore.QRect(20, 900, 241, 71))
        self.bg_4.setStyleSheet("background-color: rgb(85, 0, 255);")
        self.bg_4.setText("")
        self.bg_4.setObjectName("bg_4")


        self.bg_5 = QtWidgets.QLabel(self.centralwidget)
        self.bg_5.setGeometry(QtCore.QRect(270, 900, 241, 71))
        self.bg_5.setStyleSheet("background-color: rgb(85, 0, 255);")
        self.bg_5.setText("")
        self.bg_5.setObjectName("bg_5")


        self.Exit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Exit_btn.setGeometry(QtCore.QRect(280, 910, 221, 51))
        self.Exit_btn.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 21pt \"MS Serif\";")
        self.Exit_btn.setObjectName("Exit_btn")


        self.black_bg.raise_()
        self.bg_2.raise_()
        self.gif_2.raise_()
        self.gif_6.raise_()
        self.gif_4.raise_()
        self.gif_5.raise_()
        self.text_time.raise_()
        self.bg_3.raise_()
        self.gif_3.raise_()
        self.gif_1.raise_()
        self.gif_7.raise_()
        self.text_temp.raise_()
        self.text_date.raise_()
        self.bg_4.raise_()
        self.start_btn.raise_()
        self.bg_5.raise_()
        self.Exit_btn.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start_btn.setText(_translate("MainWindow", "START"))
        self.Exit_btn.setText(_translate("MainWindow", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
